# Generated by Django 5.2.1 on 2025-06-04 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credor',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='credor',
            name='matricula',
        ),
    ]
