# Generated by Django 5.2.1 on 2025-05-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='referente_periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
