# Generated by Django 5.2.1 on 2025-05-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_referente_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='referente_periodo',
            new_name='periodo',
        ),
    ]
