# Generated by Django 5.2.1 on 2025-06-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_referente_periodo_employee_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
