# Generated by Django 5.2.1 on 2025-06-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='periodo',
            field=models.CharField(default='05/2025', max_length=20),
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='core.employee')),
            ],
        ),
    ]
