# Generated by Django 5.2.1 on 2025-06-03 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.CharField(default='05/2025', max_length=20)),
                ('enviado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimentos', to='core.Credor')),
            ],
        ),
    ]
