# Generated by Django 5.2.1 on 2025-06-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_credor_cpf_remove_credor_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='credor',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
