# Generated by Django 5.2.1 on 2025-06-06 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_credor_email_alter_credor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pgc', models.PositiveIntegerField()),
                ('periodo', models.CharField(max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='core.credor')),
            ],
        ),
    ]
