# Generated by Django 5.2.1 on 2025-06-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicopgc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credor',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicopgc',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rendimento',
            name='periodo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
