# Generated by Django 5.2.1 on 2025-06-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grupo_credor_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPagadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curto', models.CharField(max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20)),
            ],
        ),
    ]
