# Generated by Django 5.1.1 on 2026-01-30 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_nome_normalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pgc', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.credor')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='core.historicopgc')),
            ],
            options={
                'unique_together': {('historico', 'credor')},
            },
        ),
    ]
